insert into countries (name,area_code,country_code) values ("Colombia","57","CO")
insert into departments (code,country_id,name) values ("CU",1,"Cundinamarca")
insert into departments (code,country_id,name) values ("AN",1,"Antioquia")
insert into departments (code,country_id,name) values ("VC",1,"Valle del Cauca")
insert into departments (code,country_id,name) values ("BL",1,"Bolívar")
insert into departments (code,country_id,name) values ("AT",1,"Atlántico")
insert into cities (department_id,name) values (1,"Bogotá")
insert into cities (department_id,name) values (2,"Medellín")
insert into cities (department_id,name) values (3,"Cali")
insert into cities (department_id,name) values (4,"Cartagena")
insert into cities (department_id,name) values (5,"Barranquilla")
insert into document_types (country_id,name) values (1,"Cédula de Ciudadanía")
insert into document_types (country_id,name) values (1,"Cédula de Extranjería")
insert into document_types (country_id,name) values (1,"Pasaporte")
insert into document_types (country_id,name) values (1,"Permiso Especial de Permanencia")
insert into contact (address_1,address_2,zip_code,city_id,country_id,department_id) values ("Calle A","Transversal B",130005,4,1,4)
insert into documents (document_type_id,number) values (1,"1143000000")
insert into phone_numbers (country_id,contact_id,number) values (1,1,"3220000000")
insert into users (contact_id,document_id,email,names,password,surname) values (1,1,"admin@admin.admin","Ian","Abcd1234*","Pineda Nieto")